- .gitignore
- lerna.json
- package.json
- packages/extension-ui/package.json
- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension/package.json
Small cosmetic change, when doing the inline edit don't make the stuff jump down.
> Adjust inline edit jumps

- packages/extension-ui/src/components/Header.tsx
- packages/extension-ui/src/components/Tip.tsx
- packages/extension-ui/src/components/defaults.ts
- packages/extension/public/popup.html
... need to stop playing, but just want something basic that looks relatively pleasing. (Really not the point atm, since the real focus is on getting the integration with the UIs working... but, well...)
> More small css tweaks

- packages/extension-ui/src/messaging.ts
- packages/extension/src/background/handlers/index.ts
- packages/extension/src/background/index.ts
- packages/extension/src/content.ts
- packages/extension/src/defaults.ts
- packages/extension/src/page/index.ts
Paves the way for consistent comms and subscriptions. (Needed to extend the interface as well as provider injection)
> Convert messaging to use ports

- README.md
- packages/extension-dapp/README.md
- packages/extension-dapp/src/compat/index.ts
- packages/extension-dapp/src/compat/singleSource.ts
- packages/extension-dapp/src/index.ts
- packages/extension-dapp/src/types.ts
- packages/extension/src/background/handlers/Tabs.ts
- packages/extension/src/background/handlers/index.ts
- packages/extension/src/background/types.ts
- packages/extension/src/page/Accounts.ts
- packages/extension/src/page/index.ts
- packages/extension/src/page/types.ts
- Closes https://github.com/polkadot-js/extension/issues/37
- Subscriptions for SingleSource are operational
- Subscriptions for actual extension on accounts
> Expose subscribe on Accounts interface

- packages/extension-dapp/src/index.ts
- packages/extension/manifest.json
- packages/extension/src/background/handlers/index.ts
- packages/extension/src/page/index.ts
> url from sender/tab, better per-extension errors

- README.md
> Firefox instructions in the Readme

- packages/extension/public/popup.html
- packages/extension/src/background/handlers/State.ts
1. closes #80 
Not particularly proud of that one.. yet I've spent some time trying to figure out what happens.. without luck. It must be a Firefox bug.. A single pixel of the height lets a vertical scroll-bar appear, which then lets an horizontal scroll-bar appear (because in FF the scroll-bar is part of the window). So 580 -> 581 solves the whole problem. Had a look at what Metamask does and their extension is 357x600 and they open a 360x620 popup :woman_cartwheeling:.
1. Now the `overflow-x: hidden` solves another scrollbar problem when having many accounts, before
after
Note that this is totally transparent for chrome..
> Hack to hide scrollbars on popups

- packages/extension-dapp/src/index.ts
closes: https://github.com/polkadot-js/extension/issues/128
The original problem comes from [here](https://github.com/polkadot-js/extension/blob/3433d5016c90321eead57eaa3d68048f3bd230b8/packages/extension-dapp/src/compat/singleSource.ts#L76). The handler is not called if the `eventListener` itself  is called once the DOM has already loaded.
For the record, it can be solved with something like
```js
document.readyState === 'complete'
? handler(resolve)
: window.addEventListener('load', () : void => handler(resolve));
```
Talking to Jaco we decided to remove this `compat` layer altogether since it's not used atm. Keeping the `compat` folder still as it could be used in the future.
> Fix web3Enable not resolving

- package.json
- packages/extension-ui/package.json
- packages/extension-ui/src/Popup/Signing/Details.tsx
- packages/extension/package.json
- yarn.lock
When the metadata cannot decode the method, don't end up with a blank screen - addresses what was found in #148 
Testing this now - it will solve the immediate problem, but we also need to add the missing types (which is the actual cause here), on a per-chain basis. So a follow-up PR for this will also be made.
EDIT: Tested with setKeys, it now works exactly as expected. This really should have been picked-up earlier. Horrible.
> Don't fail outright on decoding

- packages/extension-ui/src/Popup/Signing/Bytes.tsx
- packages/extension-ui/src/Popup/Signing/Extrinsic.tsx
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension/src/background/RequestBytesSign.ts
- packages/extension/src/background/RequestExtrinsicSign.ts
- packages/extension/src/background/handlers/Extension.ts
- packages/extension/src/background/handlers/State.ts
- packages/extension/src/background/handlers/Tabs.ts
- packages/extension/src/background/types.ts
- packages/extension/src/page/Signer.ts
Fixes #115 
With the following interface:
```ts
export interface RequestSign {
inner: SignerPayloadJSON | SignerPayloadRaw;
sign(pair: KeyringPair): { signature: string };
}
```
`extension` package abstracts the signing procedure using the `sign` method and because `extension-ui` needs to be aware if it is dealing with an extrinsic or a bunch of bytes, `inner` returns the inner payload content of its implementations.
> Implement signRaw

- packages/extension-ui/src/components/Address.tsx
- packages/extension/public/index.html
Part of https://github.com/polkadot-js/extension/issues/414 - allows the addresses to be fuly visible at all time while allow more space for actual names & derivation paths.
> Extend popup width

- packages/extension-ui/src/components/BackButton.tsx
fixing the following where the back arrow in not showing on the button.
> Fix back buttonnot appearing

- packages/extension-base/src/background/handlers/Extension.test.ts
- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
Add `pri(accounts.changePassword)` request type, which enables changing accounts encryption password in one go. We need it in our fork of this wallet and we thought it could be useful!
> add pri(accounts.changePassword) message

- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-base/src/background/types.ts
- packages/extension-base/src/defaults.ts
- packages/extension-base/src/page/index.ts
- packages/extension-base/src/utils/index.ts
- packages/extension-base/src/utils/isXmlOrPdf.test.tsx
- packages/extension-base/src/utils/isXmlOrPdf.ts
- packages/extension-inject/src/index.ts
- packages/extension-ui/src/Popup/PhishingDetected.tsx
- packages/extension-ui/src/Popup/index.tsx
- packages/extension/package.json
- packages/extension/src/page.ts
- yarn.lock
closes #464 
Comments / questions
- not happy with the `View` that makes the text shrinked on a 560px centered window. The most straight forward solution I thought about (not great though) was to use a bare html page to render without React, but that's additional styling etc to maintain, so left it as is for now.
- Unlike Metamask, I did not want to add a button to `still allow this website`.
> Add phishing site detection, redirection and information

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
- packages/extension-base/src/defaults.ts
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/Popup/Signing/Unlock.tsx
- packages/extension-ui/src/messaging.ts
- renaming to make things clear `savePass` is an action, whether the password is needed or not is told by the `isLocked` on the pair
- use an "updateCache" function that is called
- when the Request popup loads (it is part of the flow when the UI calls `isLocked`)
- right before signing to avoid the security issue of having the account unlocked potentially longer than the set period.
- edit the Popup is aware of the cache duration and starts a timeout until the account gets locked. 
- ~~I've been testing the event when you open the popup request before the cache expires (no password needed) and wait until it expires --> signing will fail. The experience would be much better if we could update the UI. This is non trivial though because it would mean changing this `isLocked` from a pull to …
> Password caching refactoring

- packages/extension-ui/src/components/Table.tsx
Simple, yet triggering my OCD each time :)
Tested that the scrollbar appears with longer content on FF and Chrome.
This make it look like the screenshot in #510
With longer content (manually added many lines to simulate a longer content)
instead of having disabled scrollbar like before:
> Remove scrollbar on signing popup

- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/Popup/Signing/Unlock.tsx
- packages/extension-ui/src/components/InputWithLabel.tsx
closes https://github.com/polkadot-js/extension/issues/487
closes https://github.com/polkadot-js/extension/issues/494
closes https://github.com/polkadot-js/extension/issues/491
- checkbox checked by default to extend the "password remember" period. Wording suggestion welcome :)
- unchecking this checkbox will lock the account after this last signature (so it's either extend, or lock after this one)
Here is a demo
- I first enter a wrong password twice, then type the right one and set to remember the password for 15min
- submit another tx, the password isn't needed, the checkbox to extend is checked, I uncheck it
- submit another tx -> password is asked.
> Refactor password error in request pop up and remember checkbox

- packages/extension-ui/src/Popup/index.tsx
Not 100% aware of the implication of this, but from what I could see there are no other implication.
We are passing the account meta (including the relevant `genesisHash`) in all our account creation methods (checked mnemonic, derive and JSON). Otherwise it'll default to substrate (42). All in all, it seems that it is only a UI thing.
> Remove deprecated util-crypto setSS58Format

- packages/extension-base/src/background/handlers/State.ts
I remember there was something special about this window height, but I can recall what it was and the internet didn't give me the answer.
In any case, this fix removes this white band at the bottom of any popup. It hadn't attract my eye so far.. and I thought I introduced it in #518 but it's also there on the live 0.34..
> Set popup window height to 600px

- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.test.tsx
- packages/extension-ui/src/components/ValidatedInput.tsx
- packages/extension-ui/src/hooks/useIsMounted.ts
closes #517 
Took me forever to notice the missing `update()` in tests and make it fail.
Interestingly, the `return` added was part of the original PR https://github.com/polkadot-js/extension/pull/299/files#diff-5ba6606e2d09b06b1994e7f7388db063bf6bb3c10bc603dd5b097bcbb61da6f9R31 and github blame doesn't show me when this was deleted, it'd be a valuable information to know if it's a mistake or if there was a good reason to do so.
> Fix error field being shown before entering any name

- packages/extension-base/src/background/handlers/State.ts
- packages/extension/public/index.html
following #520 
- The external window is now back to 621px, the popup is still 600px as before.
- I've set a couple `height:100%` to prevent the empty space at the bottom that made me propose #520. 
- This `min-height 600px` was necessary for the poup to be at 600 (it was all shrink otherwise).
- Looks good on FF and Chrome although interestingly the popup is 620 on Firefox, not 621
> Window height back to 621 and set 100%

- packages/extension-base/src/background/handlers/State.ts
- packages/extension/public/index.html
- packages/extension/public/notification.html
This gets us, I think to the best possible scenario, where the notification window is set to 621px, no white bar for me, the extension popup (when clicking the icon) is fixed 600px and scrollable.
For the record, an extension popup windows (when clicking the icon) can't be higher than 600px.
> Add a dedicated notification index

- packages/extension-ui/src/components/Address.tsx
was like this after #523 
Gets us back to
> Hide visibility button on signing popup

- packages/extension-ui/src/Popup/Authorize/Request.tsx
- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.test.tsx
- packages/extension-ui/src/Popup/CreateAccount/Mnemonic.tsx
- packages/extension-ui/src/Popup/Derive/Derive.test.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
- packages/extension-ui/src/Popup/Export.tsx
- packages/extension-ui/src/Popup/Forget.tsx
- packages/extension-ui/src/Popup/Metadata/Request.tsx
- packages/extension-ui/src/Popup/Signing/Unlock.tsx
- packages/extension-ui/src/components/InputWithLabel.tsx
- packages/extension-ui/src/components/TextInputs.ts
- packages/extension-ui/src/components/ValidatedInput.tsx
- packages/extension-ui/src/components/Warning.tsx
- closes #540
- refactor to unify the input error and warning
- fly-by bug fix
This is how a warning + error looks like on signing
And here on the derivation flow
> unify warning and error and add capslock warning

- packages/extension-ui/src/components/Address.tsx
closes #574
I'll log an issue, it'd help a lot to have test on such complex and important components as `Address`
> Use account info to retrieve genesisHash in forget or export

- packages/extension-ui/src/Popup/Export.test.tsx
- packages/extension-ui/src/Popup/Export.tsx
- packages/extension-ui/src/Popup/Forget.tsx
closes #593 
- add loader to "forget button" (it's too quick on my computer, I can't even see it)
- add error to export with wrong password
- add tests for the above
> Show error upon wrong password on Export screen

- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-base/src/utils/canDerive.ts
- packages/extension-base/src/utils/index.ts
- packages/extension-ui/src/Popup/Accounts/Account.test.tsx
- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/Popup/Derive/Derive.test.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
- packages/extension-ui/src/Popup/index.tsx
An oversight from #560
We were still able to select an eth account as parent, and the `master` account, which is the default one selected when using the general "derivation menu" defaulted to the first account in the hierarchy, which could have been an eth one.
> Prevent eth accounts to be selected for derivation

- packages/extension-ui/src/components/Address.test.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/util/getParentNameSuri.ts
we've now covered most use-cases I think with:
- showing info from metadata (happens on signing popup)
- showing parent info (on main account overview only)
> Some more tests for the Address component

- packages/extension-base/src/background/handlers/State.ts
Brave browser has native support for ipfs:// and ipns:// urls but this assertion is currently blocking. Updated to support them. Untested.
> Support ipfs and ipns urls

- packages/extension-base/src/background/handlers/index.ts
Our custom wallet delegates handling of standard messages to polkadot-js library. The hard-coded reference to `PORT_EXTENSION` create a port name collision when users have multiple wallets installed. This change will allow us to provide the polkadot-js handler with our wallet's custom port name to avoid this collision.
Our target usecase: https://github.com/PolymathNetwork/polymesh-wallet/pull/126/files#diff-fdfafa0e47eeeae377557dd534aa80a02af8257fb509ab33f2d44b296e2b5bddL37
> ✨ allows background handler to handle custom extention port name

- packages/extension-base/src/background/handlers/State.ts
An unauthorized app may send a large number of the "pub(authorize.tab)" request in a row to cause a denial of service, since each request launches a new popup. The app might send this request in a large volume that extension user never gets a chance to approve or reject those requests.
> Prevent unauthorized apps from abusing pub(authorize.tab) request

- packages/extension-ui/src/Popup/Accounts/index.tsx
- packages/extension-ui/src/Popup/AuthManagement/index.tsx
- packages/extension-ui/src/components/InputFilter.tsx
- packages/extension-ui/src/partials/Header.tsx
closes https://github.com/polkadot-js/extension/issues/830
I did not implement the search by address, because I'd like to have your opinion first.
The account store has addresses with 42 prefix encoding, and searching by address would mean to 
- try to decode what the user types in the search field
- if this yields a public key, re-encode it using the 42 prefix
- filter based on this
I think this could really help, even novice users that have issues understanding the whole ss58 encoding, but this adds some overhead for most of the searches, which most probably won't be by address. What do you think?
Here's how it looks right now:
https://user-images.githubusercontent.com/33178835/133886994-ecc383c5-b453-4fa3-a8cc-240709eff4b4.mp4
> Add account filtering feature

- CHANGELOG.md
- package.json
- packages/extension-base/package.json
- packages/extension-chains/package.json
- packages/extension-compat-metamask/package.json
- packages/extension-dapp/package.json
- packages/extension-inject/package.json
- packages/extension-mocks/package.json
- packages/extension-ui/package.json
- packages/extension/package.json
- yarn.lock
Closes https://github.com/polkadot-js/extension/issues/945
Needs https://github.com/polkadot-js/dev/pull/545
> Correct mocks as a dev dependency (0.42.4 patch)

- packages/extension-ui/src/Popup/Derive/AddressDropdown.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/hooks/useOutsideClick.ts
- packages/extension-ui/src/partials/Header.tsx
Closes https://github.com/polkadot-js/extension/issues/1058
Because of the state batching, you need to check both the icon and menu references to ensure that we don't untoggle.
cc @Tbaut - a check would be worth-while, it does seem to fix it for me.
> Adjust useOutsideClick with multi-references

- packages/extension-dapp/src/bundle.ts
As per [this comment](https://github.com/polkadot-js/extension/pull/1063#issuecomment-1127628581), we certainly didn't handle the rejections correctly. 
This is actually critically important since these error would come from external user-supplied code, i.e. the callback is passed in from the user and any failures shouldn't make our side of the fence break.
> Handle possible promise rejections/callback throws with logging

- packages/extension-ui/src/components/RemoveAuth.tsx
Hello, this PR fix removeAuth button UI, I've:
- align icon with text
- reduce icon size
- remove unused code
- show cursor
**before**
**after**
> fix(RemoveAuth): icon cursor & size

- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-ui/src/Popup/AuthManagement/WebsiteEntry.tsx
- packages/extension/public/locales/en/translation.json
Follow-up for https://github.com/polkadot-js/extension/pull/1068
Tested by going to 0.44.1, reject/approve and then running latest
> Handle migration from old all-accounts

- packages/extension-ui/src/components/Checkbox.tsx
I found a small bug with the indeterminate state, here is when it happened
:heavy_check_mark:  When selecting only some accounts -> checkbox is indeterminate
:heavy_multiplication_x: When manually deselecting all account -> checkbox is still indeterminate whereas it should be unchecked
After the fix:
https://user-images.githubusercontent.com/33178835/178993235-1c789439-0300-444f-8d94-d019023a9bae.mp4
> Fix indeterminate state not reseting on account selection

- CHANGELOG.md
- package.json
- packages/extension-base/src/defaults.ts
- packages/extension-base/src/stores/Accounts.ts
- packages/extension-base/src/stores/Metadata.ts
- packages/extension-base/src/utils/getId.ts
- packages/extension/webpack.shared.cjs
Based on feedback, it would seem that there are some extensions out in the wild that does not add the `EXTENSION_PREFIX` environment variable and thus responds to all the same messages as the polkadot-js extension.
Change the build to include the ENV variable as part of the webpack build and by default on the extension so at least it does not respond to their messages. (If the variable is not supplied, it will try and retrieve it via the manifest). The base package will now throw and error if _not_ specified.
TL;DR Bugfix for mis-configured using the base packages, not sure how wide-spread this is.
cc @shawntabrizi
> Adjust extension ports

- .gitignore
- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/types.ts
- packages/extension-ui/src/Popup/Authorize/Request.tsx
closes #1132
I went for an additional key in the `AccountJson` type to avoid any additional message passing.
> Remember last account selection for authorization

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-base/src/background/handlers/index.ts
- packages/extension-base/src/background/types.ts
- packages/extension-ui/src/Popup/Accounts/index.tsx
- packages/extension-ui/src/components/themes.ts
- packages/extension-ui/src/messaging.ts
- packages/extension-ui/src/partials/Header.tsx
- packages/extension/src/background.ts
- Issue: when a set of accounts are shared with a dapp, it is not easy for users to change the authorized accounts, it takes several clicks and it is error prone to search for the website manually. They'd have to go to setting > website management > find the current url > click on the number of accounts.
- Solution: when the current tab is a website that has been connected to in the past, show a "Connected" button in the header that will lead the the website management of the associated Dapp right away.
This issue has been reported to me by a user testing master, and I saw this issue coming back then here https://github.com/polkadot-js/extension/issues/1037#issuecomment-1081834987
I have tested this heavily with Brave and Firefox in light and dark mode.
The header is hidden when search is …
> Add link to accounts connected to the current tab in the header

- packages/extension-ui/src/Popup/AuthManagement/AccountManagement.tsx
- packages/extension-ui/src/Popup/index.tsx
- packages/extension-ui/src/partials/Header.tsx
When coming from the home (by clicking on the new "connected" button), changing the set of connected accounts would then redirect to the "Website Management" page. This is unexpected since the users came from the home directly.
Using `goBack` here fixes this unexpected behavior.
> Use go-back instead of going to overview from the auth management

- packages/extension-ui/src/Popup/Signing/Request/SignArea.tsx
- packages/extension-ui/src/Popup/Signing/Request/index.tsx
- packages/extension/public/locales/en/translation.json
This PR reverts https://github.com/polkadot-js/extension/pull/1053 now that Signer supports raw bytes signing again thanks to  https://github.com/paritytech/parity-signer/pull/1332 
Small bonus, I added an error message in case the account has no `genesisHash` associated. This is mandatory for QR generation and is a common source of confusion. Before having this message, the screen would only show the bytes, with no signing button or QR code, leaving users with no clue about what's going on. 
I tested it with Signer `master` branch, Polkassembly and the Signing tool of apps.
> Allow QR signing and add error when the account has no genesis

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
- packages/extension-chains/src/bundle.ts
Use the actual registry assigned to a specific instance of metadata for signing operations.
Closes #1090 (Replaces) 
Closes #907
> Always set metadata before signing

- packages/extension-ui/src/components/ErrorBoundary.tsx
Occured is the misspelled form of Occurred.
> Correct a typo

- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.spec.tsx
- packages/extension-ui/src/Popup/CreateAccount/Mnemonic.tsx
- packages/extension-ui/src/components/BoxWithLabel.tsx
- packages/extension-ui/src/components/MnemonicSeed.tsx
_context:_
the browser stores input/textarea values in tabs into plain text files in disk to restore content in case of a browser crash, unexpected closing or session restore. Multiple wallets and signers used textarea to show the generated Mnemonic Phrase seeds, obtaining the risk of getting into a situation like [this](https://halborn.com/halborn-discovers-critical-vulnerability-affecting-crypto-wallet-browser-extensions/).
_proposal:_
show the Mnemonic Phrase seed in a non input type HTML Element to avoid leaking of phrase in the cases mentioned before. With this change, it looks the same and for the user should not represent any change, there is a TODO related to the approach to the clipboard, as I still haven't check if using the Clipboard API requires asking for the additional …
> change textarea for div to show the mnemonic seed

- README.md
- package.json
`yarn watch` has been inoperable for a very long time. This removes the dangling `yarn watch` & `yarn start` that still referenced the (long removed) config.
As reported in https://github.com/polkadot-js/extension/issues/1294
> Remove old/deprecated watch (only use build)

- packages/extension-base/src/background/handlers/index.ts
We cannot rely on `sender.tab.url` when chrome preloads and prerenders pages as it will not match the url of the site being loaded. This PR changes the primary from to `sender.url` and only uses `sender.tab.url` if `sender.url` is not available.
See discussion in #1293 
Edit:
Also PR #1278 introduced a bug by adding
```
if (!sender) {
throw new Error('Unable to extract message sender');
}
```
in the case of [getActiveTabs](https://github.com/polkadot-js/extension/blob/128738181afb5796e326632c60f861e278e6481b/packages/extension/src/background.ts#L32) no port is passed causing this to throw an error preventing the extension from initializing.
This PR fixes that by only throwing `if (!isExtension && !sender)`
> Fix: Prevent authorization request from incorrect origin due to chrome pre-rendering fixes #1293 

- packages/extension-ui/package.json
- packages/extension-ui/src/Popup/Signing/Extrinsic.tsx
- yarn.lock
Follow up to: https://github.com/polkadot-js/extension/pull/1331
Displays the asset id in XCM format if it can be parsed. 
Note you can still expand the box to see the whole thing.
> feat: display asset id in xcm format

- packages/extension-compat-metamask/package.json
- yarn.lock
We are relying on `extension-compat-metamask` in our project to interact with MetaMask. However, the old `web3` dependency triggers dependabot alerts that can't be solved without upgrading.
We built a [custom package](https://www.npmjs.com/package/@logion/extension-compat-metamask) from the code in this PR (happy to remove it as soon as a new release contains this change) for testing the upgrade and everything seems to work as expected.
> Upgrade `web3` dependency in `extension-compat-metamask`

- .github/workflows/pr-any.yml
- .github/workflows/push-master.yml
- .yarnrc.yml
- README.md
- package.json
closes: https://github.com/polkadot-js/extension/issues/1370
The following PR:
- Adds instructions for Firefox to build the exact build from the zipped source code
- Adjusts the source build script to ensure you can build from source.
- Adjusts .yarnrc.yml to ensure all config works in a bare enviornment
> Add firefox installation from src instructions

- packages/extension-base/src/background/handlers/Extension.ts
closes #1376 
I managed to reproduce, here are the details for this to happen:
- you need a state with the old version of the extension where you have a non empty `authUrls` list, which means that you have ever connected at least an account to a dapp. Checkout commit 4edd9cd34face13d09a6c1c64edfc6797db800a1 for instance.
- once this is done, upgrade the extension to master: there's no state migration per se
- if you ever visit a website you had visited before, one that is present in your `authUrls`, then you'll need to set the authorizations for this website again, as in, it used to be available for all accounts, now you need to specify. Doing so will set `authorizedAccounts` for this website.
- if you try to forget an account, and you have at least one entry in your `authorizedAccounts` …
> Fix: forget account for legacy account without authorizedAccounts

- README.md
- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-ui/src/Popup/ImportLedger.tsx
- packages/extension-ui/src/Popup/index.tsx
- packages/extension-ui/src/components/Identicon.tsx
- packages/extension-ui/src/components/contexts.tsx
- packages/extension-ui/src/hooks/useLedger.ts
- packages/extension-ui/src/i18n/i18n.ts
- packages/extension-ui/src/partials/MenuSettings.tsx
- packages/extension/src/background.ts
This PR works to adjust the imports for modules part of the `@polkadot/ui` library. The reason for this is because when firefox compares the zipped libraries we create for them there are inherent differences. These diffs come from the fact that when an import is like:
`import foo from 'bar'`
the bundled code points to absolute paths in the local file system.
Instead we want to ensure its like:
`import { foo } from 'bar'`
so that it can be deterministic and the build is the same for all machines.
Note: We were a bit lucky the ui library exported everything in multiple ways or else we would have had to make a release there.
> Adjust ui imports for deterministic bundling

- eslint.config.js
- package.json
- packages/extension-base/package.json
- packages/extension-base/src/background/handlers/Extension.spec.ts
- packages/extension-dapp/package.json
- packages/extension-dapp/src/wrapBytes.spec.ts
- packages/extension-inject/package.json
- packages/extension-inject/src/cyrb53.spec.ts
- packages/extension-ui/package.json
- packages/extension-ui/src/Popup/Accounts/Account.spec.tsx
- packages/extension-ui/src/Popup/Authorize/Authorize.spec.tsx
- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.spec.tsx
- packages/extension-ui/src/Popup/Derive/Derive.spec.tsx
- packages/extension-ui/src/Popup/Export.spec.tsx
- packages/extension-ui/src/Popup/ImportQr.spec.tsx
- packages/extension-ui/src/Popup/ImportSeed/ImportSeed.spec.tsx
- packages/extension-ui/src/Popup/Signing/Signing.spec.tsx
- packages/extension-ui/src/components/AccountNamePasswordCreation.spec.tsx
- packages/extension-ui/src/components/Address.spec.tsx
- packages/extension-ui/src/components/ErrorBoundary.tsx
- packages/extension-ui/src/messaging.spec.ts
- packages/extension-ui/src/partials/Header.spec.tsx
- packages/extension-ui/src/util/buildHierarchy.spec.ts
- packages/extension-ui/src/util/nextDerivationPath.spec.ts
- tsconfig.base.json
- yarn.lock
Fixes: #1386
- Error boundary had a type export error so had to refactor it to functional component.
- ~~adds jest/@types/jest to resolve compiler error after node resolution change.~~
- Replace usages of `/// <reference types="@polkadot/dev-test/globals" />` with `import '@polkadot/dev-test/globals.d.ts';` and adds `'import/extensions': 'off'` to eslint config. This is required to resolve type issues.
---
`import/extensions` is also a useless eslint rule and will be superseded by native node esm resolution. see https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md#when-not-to-use-it
> chore: update module resolution to bundler

- packages/extension/manifest_firefox.json
Updated `manifest_firefox.json` to include:
```
"browser_specific_settings": {
"gecko": {
"id": "polkadotjavascript@gmail.com",
"strict_min_version": "108.0.2"
}
},
```
rel: #1395 
NOTE: `strict_min_version` set to `108.0.2` for no other reason than it being released on Jan 5 2023, and >1 year of support seems reasonable enough.
> fix(bug): updated `manifest,json` for Firefox

- packages/extension/manifest_firefox.json
The ID in the manifest field is wrong since we didn't use the email in the past. In this case its the embedded id set by Firefox in the past.
> Set firefox manifest id to correct embedded ID

- packages/extension/manifest_firefox.json
For manifest v3 the id required brackets....
> Fix ID for firefox with brackets

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/handlers/Tabs.ts
> Update subscribed accounts when connected site authorizations are modified

- packages/extension-ui/src/messaging.ts
- packages/extension/src/background.ts
This sends a message to wake up the `service_worker` when it has been terminated by the spec of the `manifest_V3`. Up to now, after 30 seconds have passed idle, the `service_worker` got terminated, and trying to access the popup would show `... loading ...`, and the user would have to close it and reopen it in order to correctly get the extension to render.
> fix(bug): extension stuck in `... loading ...` screen after `service_worker` got terminated

- .github/workflows/pr-any.yml
- .gitignore
- package.json
- scripts/diff-ci.sh
- scripts/diff.sh
closes: https://github.com/polkadot-js/extension/issues/1427
You can also run this script locally as well by doing: `yarn diff`
> Add CI script to check for diffs in src vs build for store release

- packages/extension-base/src/utils/portUtils.ts
- packages/extension-ui/src/Popup/index.tsx
- packages/extension-ui/src/messaging.spec.ts
- packages/extension-ui/src/messaging.ts
- packages/extension/src/background.ts
- packages/extension/src/content.ts
This builds on the approach taken in #1424 but instead of only doing it once when opening the popup it does it before any message over a port from either the extension UI or content script. This prevents attempting to send message over disconnected ports or while the service worker is idle or terminated and **should** hopefully close multiple open issues including #1432, #1420, #1417, #1416, #1415.
This PR does not add a heartbeat to the service worker so if there are transactions that may take a long time to return it is still possible the service worker may timeout and become idle however I've not seen instance of this from my testing as when connected to a dApp there is a ping message being sent every 5 seconds.
secondly I added a check filter out non http url when setting an active …
> Fix: ensure the service worker is awake before every port message

- README.md
Removes the diff instructions in the readme for ff. This is because the CI will now always check to ensure there are no diffs in the src and master builds for ff store review.
rel: https://github.com/polkadot-js/extension/pull/1429
> Remove Diff instructions in README in favor of CI

- packages/extension-ui/src/Popup/index.tsx
Send a `ping` message to create a port that will be reused for subsequent messages when the popup is opened. If a port doesn't exist already the `Promise.all` for subscriptions will result in multiple parallel requests to create ports which then triggers the onConnect listener multiple times.
> Send ping before subscriptions

- packages/extension-ui/src/Popup/Signing/Request/SignArea.tsx
- packages/extension-ui/src/components/Toast/ToastProvider.tsx
in PR #1367 `setTimeout` was replaced with `chrome.alarms` in both the `SignArea` and `ToastProvider` components. Manifest V3 only recommends against the use of `setTimeout` in service workers / background scripts as the scripts don't run continuously. For front end UI components where the timeout is only required while the UI component is active `setTimeout` is still fine to use.
Currently with the `ToastProvider` it is trying to create an alarm of 1.5 seconds. The minimum `chrome.alarms` duration is 30 seconds so this is throwing a console error
> Alarm delay is less than the minimum duration of 30 seconds. In packed extensions, alarm "toastAlarm" will fire after the minimum duration.
Also the code is creating and then removing it straight away and is in a useEffect that only runs once …
> Fix SignArea and ToastProvider timeout

- packages/extension-chains/src/bundle.ts
This fixes a bug where the rawMetadata would reset the registry properties, and set the addresses to `ss58: 42` when metadata was updated. This fixes the following so that it no longer happens.
> Fix setting rawMetadata as registry metadata

- packages/extension/src/page.ts
> fix: extension does not get injected on page load

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/types.ts
- packages/extension-ui/src/Popup/AuthManagement/AccountManagement.tsx
- packages/extension-ui/src/Popup/Authorize/Request.tsx
- packages/extension-ui/src/Popup/Authorize/index.tsx
- packages/extension-ui/src/messaging.ts
- packages/extension-ui/src/partials/AccountSelection.tsx
- packages/extension/public/locales/en/translation.json
PR #1453 added the ability to reject an authorization request, which is valuable as it throws an error that can be handled by the request originator. However, the current behavior still adds the site to the list of authorized sites, which may not always be desired.
This PR adds a new message handler `pri(authorize.cancel)` that:
- Deletes the authorization request (similar to previous `pri(authorize.delete.request)`)
- Rejects the authorization request with an error
= Does NOT add the URL to the list of authorized sites
The key difference is that users can now completely cancel an authorization attempt without having the site appear in their authorized sites list. The site will also prompt for authorization again for future attempts to connect the extension.
> Add support for canceling authorization requests without authorizing sites

- packages/extension-ui/src/partials/AccountSelection.tsx
- packages/extension-ui/src/util/sanitizeOrigin.ts
- packages/extension/public/locales/en/translation.json
This pull request improves the sanitization of the dApp origin string displayed in the Polkadot extension's Enable access request dialog. Previously, certain HTML tags like `<br>` were not properly sanitized, allowing attackers to inject line breaks and other HTML, which could be exploited to spoof the origin and deceive users.
Unsanitized content in the origin display is a security risk as it can be exploited to visually mislead users into authorizing malicious dApps. This fix closes that attack vector by enforcing strict sanitization, thereby improving user safety and trust in the extension.
1. Access any webpage and open the browser's DevTools. (Make sure you have polkadot.js extension)
2. Execute the JavaScript code.
```ts
await injectedWeb3["polkadot-js"].enable( …
```
> Sanitize dApp origin to prevent spoofing

- packages/extension-base/src/background/handlers/State.ts
- packages/extension-mocks/src/chrome.ts
This pull request resolves a security vulnerability where the extension failed to distinguish between a dApp's secure (`https`) and insecure (`http`) origins. By authorizing a site like `https://dapp.com`, a user would unknowingly also authorize `http://dapp.com`. This flaw could be exploited in a Manipulator-in-the-Middle (MitM) attack, where an attacker redirects a user to the insecure version of the site and injects malicious code to interact with the extension under the guise of the trusted origin.
The root cause was the `stripUrl()` function, which removed the protocol from the URL, leaving only the hostname as the identifier. The fix modifies this function to preserve the protocol (`https://` or `http://`) as part of the origin string. This change ensures that each origin is treated …
> fix: Enforce distinct authorization for HTTP and HTTPS origins
