polkadot-js/extension

- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/Popup/Forget.tsx
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/components/Button.tsx
- packages/extension-ui/src/components/defaults.ts
> Adjust some styling

- packages/extension/public/popup.html
- popup height < max allowed 600
> Additional tiny style enhancements

- .travis.yml
- packages/extension-dapp/LICENSE
- packages/extension-dapp/README.md
- packages/extension-dapp/package.json
- packages/extension-dapp/src/index.ts
- packages/extension-dapp/src/types.ts
- packages/extension-ui/LICENSE
- packages/extension-ui/README.md
- packages/extension/LICENSE
- packages/extension/README.md
- packages/extension/src/inject/Accounts.ts
- packages/extension/src/inject/Injected.ts
- packages/extension/src/inject/Signer.ts
- packages/extension/src/inject/index.ts
- packages/extension/src/inject/types.ts
- tsconfig.json
Closes https://github.com/polkadot-js/extension/issues/27
> Add @polkadot/extension-dapp

- packages/extension-ui/package.json
- packages/extension/package.json
- packages/extension/src/background/handlers/Extension.ts
- yarn.lock
Including https://github.com/polkadot-js/common/pull/419
> Bump api, common & ui

- packages/extension/package.json
- packages/extension/src/background/handlers/State.ts
- yarn.lock
As the title suggests, requests now make a auth window appear - https://www.youtube.com/watch?v=k51L2Qx5rvw&feature=youtu.be
> Requests create an auth popup window

- package.json
- packages/extension-ui/package.json
- packages/extension/package.json
- packages/extension/src/background/handlers/State.ts
- yarn.lock
Closes https://github.com/polkadot-js/extension/issues/77
> Remove popup focus

- packages/extension-ui/src/Popup/Signing/Details.tsx
- packages/extension/package.json
- packages/extension/src/background/handlers/Extension.ts
- packages/extension/src/page/Signer.ts
- yarn.lock
Closes https://github.com/polkadot-js/extension/issues/73
> Re-enable mortals

- packages/extension/src/background/index.ts
As changed in https://github.com/polkadot-js/ui/pull/159
> Import store directly

- packages/extension-ui/package.json
- packages/extension-ui/src/components/Address.tsx
- packages/extension/package.json
- yarn.lock
Closes #89
Both Kusama and Substrate displayed -
> Fix name display for other prefixes

- README.md
> Faq for seed

- packages/extension/src/background/handlers/State.ts
- packages/extension/src/background/handlers/Tabs.ts
Fix https://github.com/polkadot-js/extension/issues/100
> Extension: reject requests from unauthorized urls

- package.json
- packages/extension-inject/src/types.ts
- packages/extension-ui/src/Popup/Signing/Details.tsx
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension/manifest.json
- packages/extension/package.json
- packages/extension/src/background/handlers/Extension.ts
- packages/extension/src/background/types.ts
- packages/extension/src/page/Signer.ts
- tsconfig.json
- yarn.lock
Closes https://github.com/polkadot-js/extension/issues/103
> Update with signPayload for injected signer

- CHANGELOG.md
- package.json
- packages/extension-ui/package.json
- packages/extension/package.json
- packages/extension/src/page/Signer.ts
- yarn.lock
- Bumps other deps as well, closes #111, closes #112 & closes #113
> Bump API, support Extrinsics v3

- CHANGELOG.md
- lerna.json
- package.json
- packages/extension-dapp/package.json
- packages/extension-inject/package.json
- packages/extension-ui/package.json
- packages/extension-ui/src/Popup/Import.tsx
- packages/extension-ui/src/messaging.ts
- packages/extension/package.json
- packages/extension/src/background/handlers/Extension.ts
- packages/extension/src/background/types.ts
- yarn.lock
Add derivation path support by allowing paths to be specified as part of the seed input 
Stop-gap for https://github.com/polkadot-js/extension/issues/14
> Add derivation path support (import)

- packages/extension-dapp/src/index.ts
- packages/extension-inject/src/types.ts
- packages/extension-ui/src/Popup/Authorize/index.tsx
- packages/extension-ui/src/Popup/Create.tsx
- packages/extension-ui/src/Popup/Import.tsx
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/Popup/Signing/index.tsx
- packages/extension-ui/src/Popup/index.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/components/contexts.tsx
- packages/extension-ui/src/components/types.ts
- packages/extension-ui/src/messaging.ts
- packages/extension/src/background/handlers/Extension.ts
- packages/extension/src/background/handlers/State.ts
- packages/extension/src/background/handlers/Tabs.ts
- packages/extension/src/background/types.ts
- packages/extension/src/page/Accounts.ts
- packages/extension/src/page/Signer.ts
- packages/extension/src/page/index.ts
Split from https://github.com/polkadot-js/extension/pull/134 (makes that PR cleaner and easier to merge)
> Split messages into pub/pri

- package.json
- packages/extension-ui/package.json
- packages/extension-ui/src/Popup/Accounts/Account.test.tsx
- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/Popup/Authorize/Request.tsx
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/components/ActionBar.tsx
- packages/extension-ui/src/components/Link.tsx
- packages/extension/package.json
- tsconfig.json
- yarn.lock
> Button alignment

- package.json
- packages/extension-base/package.json
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/stores/Base.ts
- packages/extension-base/src/background/stores/Metadata.ts
- packages/extension-ui/package.json
- packages/extension/package.json
- yarn.lock
Make store generic for extended use, e.g. https://github.com/polkadot-js/extension/issues/310
> Introduce base store (with key prefix mgmt)

- CHANGELOG.md
- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
- packages/extension-ui/src/Popup/Accounts/Account.test.tsx
- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/Popup/Accounts/AccountsTree.tsx
- packages/extension-ui/src/Popup/Derive/index.tsx
- packages/extension-ui/src/Popup/index.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/components/Link.tsx
- packages/extension-ui/src/utils/buildHierarchy.ts
Closes https://github.com/polkadot-js/extension/issues/346
> Display child when parent has been removed

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
- packages/extension-chains/src/genesisHashes.ts
- packages/extension-chains/src/index.ts
- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/hooks/useMetadata.ts
- packages/extension-ui/src/messaging.ts
- Closes https://github.com/polkadot-js/extension/issues/10
- Closes https://github.com/polkadot-js/extension/issues/212
- Closes https://github.com/polkadot-js/extension/issues/213
> Tie account to genesis

- packages/extension-chains/src/chains.ts
website:
https://darwinia.network/
telemetry:
https://telemetry.polkadot.io/#/Crab
explorer:
https://crab.subscan.io/block/0
> add crab network

- CHANGELOG.md
- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/Popup/Signing/Unlock.tsx
- packages/extension-ui/src/components/Checkbox.tsx
- packages/extension-ui/src/components/InputWithLabel.tsx
- packages/extension-ui/src/messaging.ts
Closes https://github.com/polkadot-js/extension/issues/274
> Don't ask for the password for 15 minutes

- CHANGELOG.md
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-ui/src/Popup/Authorize/Request.tsx
- packages/extension-ui/src/Popup/CreateAccount/AccountName.tsx
- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.test.tsx
- packages/extension-ui/src/Popup/CreateAccount/Mnemonic.tsx
- packages/extension-ui/src/Popup/CreateAccount/index.tsx
- packages/extension-ui/src/Popup/Derive/AddressDropdown.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
- packages/extension-ui/src/Popup/Derive/index.tsx
- packages/extension-ui/src/Popup/ImportQr.tsx
- packages/extension-ui/src/Popup/ImportSeed.tsx
- packages/extension-ui/src/Popup/RestoreJson.tsx
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/components/MnemonicSeed.tsx
- packages/extension/public/index.html
Part of https://github.com/polkadot-js/extension/issues/414
> Display accounts first-and-foremost on all creations

- packages/extension-dapp/src/index.ts
linked to https://github.com/polkadot-js/extension/issues/409
Is that totally useless @jacogr ?
> Throw error for undefined name in web3Enable

- CHANGELOG.md
- packages/extension/webpack.config.js
No idea wtf I'm doing... attempting to do something about https://github.com/polkadot-js/extension/issues/440
> Swap order flag

- CHANGELOG.md
- packages/extension/webpack.config.js
Still clueless, but the last one seemed closer? Still trying https://github.com/polkadot-js/extension/issues/440
> Use moduleIds: 'deterministic' for webpack

- CHANGELOG.md
- packages/extension/webpack.config.js
Closer, but nowhere near there yet... more attempts for https://github.com/polkadot-js/extension/issues/440
> Adjust contenthash flags

- CHANGELOG.md
- package.json
- packages/extension-ui/package.json
- yarn.lock
Mucking about for https://github.com/polkadot-js/extension/issues/440
> Remove safe-buffer duplicates

- CHANGELOG.md
- packages/extension/webpack.config.js
Part of https://github.com/polkadot-js/extension/issues/440
> Natural id order?

- packages/extension-dapp/src/index.ts
- packages/extension-inject/README.md
- packages/extension-inject/src/types.ts
closes https://github.com/polkadot-js/extension/issues/250
> Add address encoding option to web3Accounts

- packages/extension-chains/src/chains.ts
website:
https://stafi.io
telemetry:
https://telemetry.polkadot.io/#list/Stafi
explorer:
https://stafi.subscan.io/block/0
> Add Stafi network

- packages/extension-ui/src/Popup/Derive/Derive.test.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
- packages/extension-ui/src/util/nextDerivationPath.ts
closes #482
There doesn't seem to be a way to test this correctly since this involves a redirection.
> Fix derive suggestion when switching root

- packages/extension-ui/src/util/buildHierarchy.test.ts
- packages/extension-ui/src/util/buildHierarchy.ts
- packages/extension-ui/src/util/getNetworkMap.ts
> Groupe accounts by network and sort by name, path, creation date

- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/Popup/Forget.tsx
- packages/extension-ui/src/Popup/ImportQr.tsx
- packages/extension-ui/src/Popup/Signing/Request.tsx
- packages/extension-ui/src/assets/arrowTopRight.svg
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/components/Identicon.tsx
closes #480 
How it looks like:
> Show a specific icon on external account

- packages/extension-base/src/utils/isXmlOrPdf.ts
sorry this slipped in my last PR, it's a value I used for test that I forgot to remove.
> Remove stray test value

- packages/extension-chains/src/chains.ts
Darwinia Mainnet
website:
https://darwinia.network/
telemetry:
https://telemetry.polkadot.io/#list/Darwinia%20CC1
explorer:
https://darwinia-cc1.subscan.io/block/0
> add darwinia network

- package.json
- packages/extension-chains/src/chains.ts
- packages/extension-chains/src/genesisHashes.ts
- packages/extension-ui/src/components/Address.tsx
- yarn.lock
closes https://github.com/polkadot-js/extension/issues/496
> Use @polkadot/networks

- docs/index.html
Consitent with the images and what's in the app.
from 
to
> Use 400 font weightfor consistancy

- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/components/Address.tsx
- packages/extension-ui/src/components/Menu.tsx
> Ability to set account visibility from main screen

- packages/extension/public/index.html
- packages/extension/public/notification.html
I'm hopeful, looks good on chrome here at least :)
> Set root height with vh instead of %

- package.json
- packages/extension-base/package.json
- packages/extension-chains/src/index.ts
- packages/extension-ui/src/Popup/Signing/Extrinsic.tsx
- packages/extension-ui/src/Popup/Signing/Request/index.tsx
- packages/extension/public/locales/en/translation.json
- yarn.lock
Also ended up bumping deps (since well, my script had them updated anyway)
> Show method decode fallback error/log

- packages/extension-ui/src/components/InputWithLabel.tsx
- packages/extension/public/locales/en/translation.json
closes #555
and another oversight with translation.
> Fix error overlap and translation

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/types.ts
- packages/extension-ui/src/Popup/RestoreJson.tsx
- packages/extension-ui/src/messaging.ts
- Use info coming from `KeyPair` (from the background script) rather than anything the file contains to be future proof, linked to #538.
- Show error on wrong file
- Show error on wrong password
> Refactor JSON restoration

- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-base/src/background/types.ts
- packages/extension-base/src/page/Accounts.ts
- packages/extension-dapp/src/compat/singleSource.ts
- packages/extension-inject/src/types.ts
> Add a flag to get any account type for InjectedAccounts interface

- packages/extension-ui/src/components/Address.tsx
> Hide too long names behind ellipsis

- packages/extension-ui/src/Popup/Derive/Derive.test.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
Closes https://github.com/polkadot-js/extension/issues/583
> Hide parent password/path when non-deriving

- packages/extension-ui/src/Popup/CreateAccount/AccountName.tsx
- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.test.tsx
- packages/extension-ui/src/Popup/CreateAccount/index.tsx
> Show the account's name typed in on Account creation screen

- README.md
linked to https://github.com/polkadot-js/docs/pull/109
> Move FAQ to docs

- packages/extension-ui/src/components/Address.test.tsx
- packages/extension-ui/src/components/Address.tsx
> Add tests for Address component

- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.test.tsx
- packages/extension-ui/src/Popup/Derive/Derive.test.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
- packages/extension-ui/src/partials/MenuAdd.tsx
> Separate derivation and creation flow

- packages/extension-ui/src/Popup/ImportQr.tsx
- packages/extension-ui/src/components/ValidatedInput.tsx
- packages/extension-ui/src/partials/Name.tsx
> Show account address and name when importing from QR

- packages/extension-ui/src/Popup/AuthManagement/WebsiteEntry.tsx
> Better color for dark theme

- packages/extension-ui/src/Popup/Derive/DerivationPath.tsx
- packages/extension-ui/src/Popup/Derive/Derive.test.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
closes #616 
Added some more tests with derivation lock.
> Prevent from typing a derivation with `///password` since it is ignored 

- packages/extension-ui/src/Popup/ImportLedger.tsx
- packages/extension-ui/src/components/Dropdown.tsx
- packages/extension/public/locales/en/translation.json
- packages/extension/public/locales/fr/translation.json
> Fix toggle offset when the dropdown has a label

- packages/extension-ui/src/Popup/ImportLedger.tsx
- packages/extension-ui/src/components/Dropdown.tsx
https://user-images.githubusercontent.com/33178835/105740969-0d406d00-5f3a-11eb-8bee-ab15cf264097.mp4
> Allow giving a name to ledger

- packages/extension-ui/src/hooks/useGenesisHashOptions.ts
- packages/extension-ui/src/messaging.ts
This partly helps for #461 
Here's an example using westend
https://user-images.githubusercontent.com/33178835/105843170-a4a7cd80-5fd7-11eb-93f5-c0b016b91db1.mp4
> Add chains in metadata

- packages/extension-ui/src/Popup/Accounts/Account.tsx
- packages/extension-ui/src/components/ValidatedInput.tsx
- packages/extension-ui/src/partials/Name.tsx
- fix input position (see below screenshot)
- allow typing "Enter" key to validate
- fix error, which had no background and was difficult to read
previously
now
https://user-images.githubusercontent.com/33178835/106025403-009e4f00-60c9-11eb-844b-38af6e6f7f52.mp4
> Fix renaming alignment and behavior

- packages/extension-ui/src/Popup/Derive/DerivationPath.tsx
- packages/extension-ui/src/Popup/Derive/SelectParent.tsx
closes #633 
https://user-images.githubusercontent.com/33178835/106121541-f5decb00-6157-11eb-8df0-f997a5d4e980.mp4
> Default path and password resets on parent change

- packages/extension-ui/src/Popup/CreateAccount/CreateAccount.test.tsx
- packages/extension-ui/src/Popup/CreateAccount/index.tsx
- packages/extension-ui/src/hooks/useGenesisHashOptions.ts
closes #638 
- keep Polkadot and Kusama at the top of the list
- tests
https://user-images.githubusercontent.com/33178835/106470721-1f259100-64a1-11eb-8624-90b078c81b9e.mp4
> Network dropdown at account creation

- packages/extension-ui/src/Popup/ImportQr.test.tsx
- packages/extension-ui/src/assets/arrowParentLabel.svg
- packages/extension-ui/src/components/Address.test.tsx
- packages/extension-ui/src/components/Address.tsx
- Use the same derive icon everywhere
- Use a QR for Signer accounts
> Icon consistency

- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-ui/src/Popup/PhishingDetected.tsx
- packages/extension-ui/src/Popup/index.tsx
> Show malicious website on the landing page

- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension/manifest.json
> Phishing redirect, tab check

- jest.config.js
- packages/extension-ui/src/Popup/Accounts/Account.test.tsx
- packages/extension-ui/src/Popup/Derive/Derive.test.tsx
- packages/extension-ui/src/Popup/Export.test.tsx
- packages/extension-ui/src/Popup/ImportSeed/ImportSeed.test.tsx
- packages/extension-ui/src/Popup/Signing/Signing.test.tsx
- silence expected console errors
- make sure state changes are wrapped into `act`
- clean deprecated config (see below)
> Fix errors or warnings appearing in tests

- packages/extension-base/src/background/RequestExtrinsicSign.ts
- packages/extension-base/src/background/handlers/Extension.test.ts
- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-chains/src/index.ts
- packages/extension-inject/src/types.ts
closes https://github.com/polkadot-js/extension/issues/631
Tests added.
> Added code to support custom signed extension/user extension

- packages/extension/public/index.html
As per https://github.com/polkadot-js/extension/issues/310#issuecomment-804360559
> Add style inside tag (not inline)

- CHANGELOG.md
- package.json
- packages/extension-base/package.json
- packages/extension-ui/src/Popup/AuthManagement/index.tsx
- packages/extension/package.json
- yarn.lock
> Also adjust auth height

- packages/extension-ui/src/Popup/Signing/Qr.tsx
- packages/extension-ui/src/Popup/Signing/Request/index.tsx
I implemented the signing support in Stylo and submitted a PR for Signer.
It's working well with apps and Polkassembly.
https://user-images.githubusercontent.com/33178835/118889678-bce08700-b8fd-11eb-9e71-5fbf285d8082.mp4
> Support signing messages for external accounts

- packages/extension-dapp/src/wrapBytes.spec.ts
- packages/extension-dapp/src/wrapBytes.ts
Closes https://github.com/polkadot-js/extension/issues/747
> Don't wrap/unwrap Ethereum-style

- packages/extension-dapp/package.json
- yarn.lock
Small helper for https://github.com/polkadot-js/extension/pull/566
(Add the deps, just ensuring that the PR doesn't have conflicts when ready, i.e. reducing merge/push work which brings no joy)
> Add web3 deps

- packages/extension-base/src/background/handlers/Tabs.ts
> Cater for # in urls

- CHANGELOG.md
- packages/extension-base/src/background/handlers/State.ts
Closes https://github.com/polkadot-js/extension/issues/841
> Ensure site authorization toggle is saved

- packages/extension-base/README.md
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/types.ts
- packages/extension-base/src/defaults.ts
- packages/extension-base/src/page/index.ts
- packages/extension-base/src/stores/Accounts.ts
- packages/extension-base/src/stores/Metadata.ts
- packages/extension-base/src/utils/getId.ts
- packages/extension-ui/src/messaging.ts
- packages/extension/src/content.ts
- packages/extension/src/page.ts
Fixes https://github.com/polkadot-js/extension/issues/858
> Add extension prefix

- packages/extension-base/src/background/handlers/Extension.test.ts
I am trying to figure out https://github.com/polkadot-js/extension/issues/907
The signature seems to be working correctly and so is the payload 🤔
> Add eth test for extension signature

- packages/extension-base/src/detectOther.ts
- packages/extension-chains/src/detectOther.ts
- packages/extension-compat-metamask/src/detectOther.ts
- packages/extension-dapp/src/detectOther.ts
As per https://github.com/polkadot-js/dev/pull/550
> introduce detectOther

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/handlers/State.ts
- packages/extension-base/src/background/types.ts
- packages/extension-ui/src/Popup/AuthManagement/WebsiteEntry.tsx
- packages/extension-ui/src/Popup/AuthManagement/index.tsx
- packages/extension-ui/src/components/RemoveAuth.tsx
- packages/extension-ui/src/components/index.ts
- packages/extension-ui/src/messaging.ts
Adds a trashcan icon to the website entry list
Introduces removeAuth and removeAuthorization functions
Resolves polkadot-js/extension#1028
Please be aware that this is my first typescript PR. Please verify.
I am open to suggestions and feedback!
polkadot address: 167o7nwjMS6WMvqpCWHK2XXvgxcMYwVhfrezw6ZbxejSmxeP
> Add authorized URL removal 

- packages/extension-ui/src/Popup/Signing/Request/SignArea.tsx
- packages/extension-ui/src/Popup/Signing/Request/index.tsx
- packages/extension/public/locales/en/translation.json
Closes https://github.com/polkadot-js/extension/issues/1052
> Drop support for QR signing

- packages/extension-ui/src/Popup/AuthManagement/AccountManagement.tsx
- packages/extension-ui/src/Popup/AuthManagement/WebsiteEntry.tsx
- packages/extension-ui/src/Popup/AuthManagement/index.tsx
- packages/extension/public/locales/en/translation.json
Fix for https://github.com/polkadot-js/extension/pull/1068
> Fix for 0 accounts on access

- packages/extension-base/src/background/handlers/Extension.ts
- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-base/src/background/types.ts
- packages/extension-base/src/page/Injected.ts
- packages/extension-ui/src/messaging.ts
Split from manifest V3 (background keep-alive check, as/when workers are killed)
> Ping on enabled extension

- packages/extension-ui/src/Popup/Accounts/index.tsx
This adds accounts addresses in the search criteria
closes https://github.com/polkadot-js/extension/issues/1171
> Add search by address

- tsconfig.webpack.json
Same config as in https://github.com/polkadot-js/apps/pull/9120
> Adjust TS target

- package.json
- packages/extension-base/package.json
- packages/extension-chains/package.json
- packages/extension-compat-metamask/package.json
- packages/extension-dapp/package.json
- packages/extension-inject/package.json
- packages/extension-mocks/package.json
- packages/extension-ui/package.json
- packages/extension-ui/src/components/ErrorBoundary.tsx
- packages/extension/package.json
- yarn.lock
Follow-up for https://github.com/polkadot-js/extension/pull/1271
Replaces & Closes https://github.com/polkadot-js/extension/pull/1270
> Bump i18next

- packages/extension-ui/src/partials/Header.tsx
closes: https://github.com/polkadot-js/extension/issues/1428
> Change Connected to Connect Accounts

- packages/extension/manifest_chrome.json
- packages/extension/manifest_firefox.json
> Remove Alarm permissions

- package.json
- packages/extension-base/package.json
- packages/extension-dapp/package.json
- packages/extension-inject/package.json
- packages/extension-ui/package.json
- packages/extension/package.json
- yarn.lock
Increases performance for the test runner, and includes fixes for deno build
> Bump dev to 0.83.2

- packages/extension-ui/src/components/Address.tsx
rel: https://github.com/polkadot-js/extension/pull/1515
> Fix `.name` error with whitescreen

- packages/extension-base/package.json
- packages/extension-base/src/background/handlers/Tabs.ts
- packages/extension-base/src/background/handlers/index.ts
- yarn.lock
This fix is inspired from https://github.com/polkadot-js/phishing/pull/5128.
> Prevent phishing validation bypass via credentialed URLs using tldts

- packages/extension-base/package.json
- yarn.lock
This PR aims to upgrade polkadot-js dependencies.
```
@polkadot/phishing -------------------------- ◯ ^0.25.19 ----- ◉ ^0.25.20 -----
```
> Bump polkadot-js deps
